name: Upload Artifacts Workflow

on:
  workflow_dispatch:  # Triggered manually from GitHub UI
  
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a file to upload
        run: echo "Hello, world!" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: hello.txt
          
      - name: List files before upload
        run: ls -alh  # This will list all files in the current directory