name: Download Artifacts Workflow

on:    
  workflow_dispatch:  # Triggered manually from GitHub UI      

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files after artifact download
        run: ls -alh  # This will list all files in the current directory after downloading the artifact
  
      - name: Download artifact
        uses: actions/download-artifact@v4  # Correct version for downloading artifacts
        with:
          name: example-artifact

      - name: Show the contents of the downloaded file
        run: cat hello.txt
