name: CI/CD Pipeline for Spring Boot with Terraform EKS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/actions/build.yml@main  # Reusable build action