name: CI/CD Pipeline for Spring Boot with Terraform EKS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    
  dockerize:
    needs: build
    uses: ./.github/workflows/docker-build-push.yml  # Call the Docker Build and Push workflow